#!/usr/bin/env bash

BASE_DIR="$(pwd)"
HOOK_FILE="$(readlink -f "$0")"
SCRIPT_DIR="$(cd "$(dirname "$HOOK_FILE")" && pwd)"
WORK_DIR="$SCRIPT_DIR/../../code"  # dir which contains the binary and cofig.json
BINARY="$WORK_DIR/testAuditor"

OUTPUT_NOTES_REF="testAudit"

while read -r oldrev newrev refname
do
    if [[ "$refname" == refs/notes/* ]]; then
        continue
    fi

    note="$(git notes show "$newrev" 2>/dev/null || true)"
    if [[ -z "$note" ]]; then
        echo "Keine Note gefunden für $newrev"
        continue
    fi
    cd "$WORK_DIR"
    if [[ ! -x "$BINARY" ]]; then
        echo "Binary nicht gefunden oder nicht ausführbar: $BINARY"
        exit 1
    fi
    output="$("$BINARY" -c "$note")"

    cd "$BASE_DIR"
    if [[ -n "$output" ]]; then
        git notes --ref="$OUTPUT_NOTES_REF" append -m "$output" "$newrev"
    fi

    echo "#hook: testAuditor added this XMl to the gitnotes in ref \"$OUTPUT_NOTES_REF:\""
    git notes --ref="$OUTPUT_NOTES_REF" show "$newrev"
done
 