from classes.ToDoList import ToDoList, ToDoItem

def test_copy():
    todo_list1 = ToDoList("Alice")
    todo_list2 = ToDoList("Alice")
    todo_list3 = todo_list1.copy()
    assert(todo_list1 == todo_list2)
    assert(todo_list1 == todo_list3)
    assert(todo_list2 == todo_list3)
    todo_list1.addItem(ToDoItem("Item 1"))
    assert(todo_list1 != todo_list2)
    assert(todo_list1 != todo_list3)
    assert(todo_list2 == todo_list3)
    todo_list2.addItem(ToDoItem("Item 1"))
    assert(todo_list1 == todo_list2)
    assert(todo_list1 != todo_list3)
    assert(todo_list2 != todo_list3)
    todo_list3.addItem(ToDoItem("Item 1"))
    assert(todo_list1 == todo_list2)
    assert(todo_list1 == todo_list3)
    assert(todo_list2 == todo_list3)
